name: Build & Release

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.js'
      - '**/*.ps1'
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout XSO assemblies
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.xsoRepo }}
          token: ${{ secrets.repoToken }}
          path: refs

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: '9.0.x'

      - name: Add Bepis NuGet & Restore dependencies
        run: |
          dotnet nuget add source https://nuget.bepinex.dev/v3/index.json
          dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      # Read the base version from VERSION file
      - name: Read version
        id: version
        shell: pwsh
        run: |
          if (-Not (Test-Path VERSION)) { Write-Error "VERSION file not found" }
          $version = (Get-Content VERSION -Raw).Trim()
          if (-not $version) { Write-Error "VERSION file is empty" }
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Create Release
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $version = "${{ steps.version.outputs.version }}"
          $short = "${{ github.sha }}".Substring(0,7)
          $tag = "$version+$short"
          $dll = 'builds/Release/net472/KeyboardOSC.dll'
          $cfg = 'BepInEx.cfg'
          if (-not (Test-Path $dll)) { Write-Error "Artifact missing: $dll" }
          if (-not (Test-Path $cfg)) { Write-Error "Artifact missing: $cfg" }

          if (Test-Path CHANGELOG.md) { $notes = Get-Content CHANGELOG.md -Raw } else { $notes = 'Automated build' }

          gh release create $tag $dll $cfg --title "KeyboardOSC $tag" --prerelease --notes-file CHANGELOG.md || Write-Error 'Release creation failed'
